# This is a config for E2B sandbox template.
# You can use template ID (kfwd5ksunobzz1eyydfa) or template name (adorable-nextjs-test2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("adorable-nextjs-test2") # Sync sandbox
# sandbox = await AsyncSandbox.create("adorable-nextjs-test2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('adorable-nextjs-test2')

team_id = "96ebfe64-a755-42ee-9c10-782ae7a0e6c9"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "adorable-nextjs-test2"
template_id = "kfwd5ksunobzz1eyydfa"
